version: "3"
services:
    frps:
      build: ./frps
      container_name: frps
      ports: 
        - "20002-20004:20002-20004"
        - "20000:80"
        - "20001:443"
      volumes:
        - ./conf:/etc/frps:ro